<?php
/**
 * @category   TechMitraa
 * @package    TechMitraa_StoreInfo
 ''
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace TechMitraa\StoreInfo\Controller\Adminhtml\Items;

class Index extends \TechMitraa\StoreInfo\Controller\Adminhtml\Items
{
    /**
     * Items list.
     *
     * @return \Magento\Backend\Model\View\Result\Page
     */
    public function execute()
    {
        /** @var \Magento\Backend\Model\View\Result\Page $resultPage */
        $resultPage = $this->resultPageFactory->create();
        $resultPage->setActiveMenu('TechMitraa_StoreInfo::test');
        $resultPage->getConfig()->getTitle()->prepend(__('Manage Offline Store Information'));
        $resultPage->addBreadcrumb(__('Offline'), __('Offline'));
        $resultPage->addBreadcrumb(__('Store'), __('Store'));
        $resultPage->addBreadcrumb(__('Information'), __('Information'));

        return $resultPage;
    }
}